platform :ios, '8.0'

# The target name is most likely the name of your project.
target 'rn_basic' do
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'RCTImage',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/lib/ios'
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
#   pod 'RNGL', :path => '../node_modules/gl-react-native'
#   pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

#   pod 'react-native-webgl', :path => '../node_modules/react-native-webgl'

  pod 'ReactNativeSearchBar', :path => '../node_modules/react-native-search-bar'

  pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end